sudo: required
language: node_js
node_js:
  - "4"

services:
  - docker

install:
  - docker --version
  - chmod 755 ./build-lambda-package.sh 
  - ./build-lambda-package.sh

script:
  - ./run-integration-tests.sh