sudo: required
language: node_js
node_js:
  - "4"

services:
  - docker

# mkdir required here to avoid permission problem in script
install:
  - mkdir -p .build/lambda/libraries 
  - ./build-lambda-package.sh

script:
  - ./run-integration-tests.sh